baseURL: https://falco.org/
languageCode: en-us
title: Falco - Container Native Runtime Security
theme: falco-fresh
publishDir: ../falcosecurity.github.io

params:
  primaryFont:
    name: "Karla"
    sizes: [400 700]
  secondaryFont:
    name: "MaaxMono"    
  hero:
    # Main hero title
    title: Container Native Runtime Security
    # Hero subtitle (optional)
    subtitle: Falco is an open source project for intrusion and abnormality detection for Cloud Native platforms such as Kubernetes, Mesosphere, and Cloud Foundry. Detect abnormal application behavior; alert via Slack, Fluentd, NATS, and more; Protect your platform by taking action through serverless (FaaS) frameworks and more.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#download"
    # Hero image (from /images/___)
    image: illustrations/falco-hero-1.png
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - src: kubernetes.svg
      alt: Kubernetes
    - src: docker.svg
      alt: Docker
    - src: rkt.svg
      alt: Rkt
    - src: helm.svg
      alt: Helm
    - src: nats.svg
      alt: Nats
    - src: kubeless.svg
      alt: Kubeless
    - src: mesosphere.svg
      alt: Mesosphere
    - src: slack.svg
      alt: Slack
    - src: fluentd.svg
      alt: Fluentd

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    cncf:
      logo: cncf-black.svg
      cncfLink: https://cncf.io
      level: Sandbox
      levelLink: https://github.com/cncf/toc/blob/master/process/sandbox.md 
    menu:  
    - title: Features
      url: "#features"
    - title: About
      url: "#about"
    - title: Download
      url: "#download"
    - title: GitHub
      url: https://github.com/falcosecurity/falco
    - title: Docs
      url: https://github.com/falcosecurity/falco/wiki
  sectionAbout:
    title: About Falco.
    summary: Falco was born from the need to better understand what action containers are performing and how to protect your container platform from possible malicious behavior. With more choice and responsibility shifting left into the development teams, security teams need to have deep insight into container activities. Falco leverages Sysdig’s open source technology to instrument the Linux kernel, and create an event stream from Linux system calls. Falco’s rules engine can then detect abnormal activity in containers, the underlying host, and the container platform.
  section1:
    title: Key Features.
    subtitle: 
    tiles:
    - title: Platform Aware
      icon: check.png
      text: Build rules specific to your Cloud Native platforms to enforce policy across all your containers & microservices.
    - title: Container-native
      icon: box.png
      text: Runtime Security built for containers. Built from the ground up to natively support containerized applications.
    - title: Deep Visibility
      icon: scalable.png
      text: Complete container visibility through a single sensor. Gain insight into application and container behavior. 
  section2:
    title: Downloads + Resources.
    subtitle: Get started today, contribute to the open source project, & learn more.
    resources:
    - title: CONTRIBUTE
      text: Jump over to our GitHub page to contribute to our open source ecosystem.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: group.png
      buttonText:  Falco Github
      buttonLink: https://github.com/falcosecurity/falco
    - title: Download
      text: Get started with our Falco installation guide.
      icon: download.png
      buttonText: Falco Install Guide
      buttonLink: https://github.com/falcosecurity/falco/wiki/How-to-Install-Falco-for-Linux
    - title: Documentation
      text: Visit our wiki where you can find information about installing Falco, configuration options, and writing custom rules.
      icon: documentation-2.png
      buttonText: Falco Wiki
      buttonLink: https://github.com/falcosecurity/falco/wiki
    - title: Connect
      text: Join our Slack team to interact with other users and developers.
      icon: group.png
      buttonText: Falco Slack
      buttonLink: https://slack.sysdig.com        
  section3:
    title: Stay up to date.
    subtitle: Sign-up for project updates.
    buttonText: Sign-up!
  footer:
    # Logo (from /images/logos/___)
    copyright: Copyright 2018, The Falco Authors
