baseURL: http://falco.org/
languageCode: en-us
title: Falco - Cloud Native Runtime Security
theme: falco-fresh
publishDir: ../falcosecurity.github.io

params:
  primaryFont:
    name: "Karla"
    sizes: [400 700]
  secondaryFont:
    name: "MaaxMono"    
  hero:
    # Main hero title
    title: Detect, Alert, Protect
    # Hero subtitle (optional)
    subtitle: Falco is an open source project for intrusion and abnormality detection for Cloud Native platforms such as Kubernetes, Mesosphere, and Cloud Foundry. Detect abnormal application behavior; alert via Slack, Fluentd, NATS, and more; Protect your platform by taking action through serverless (FaaS) frameworks and more.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#download"
    # Hero image (from /images/___)
    image: illustrations/falco-hero-1.png
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - src: nats.svg
      alt: Nats
    - src: kubeless.svg
      alt: Kubeless
    - src: helm.svg
      alt: Helm
    - src: rkt.svg
      alt: Rkt
    - src: mesosphere.svg
      alt: Mesosphere
    - src: docker.svg
      alt: Docker
    - src: slack.svg
      alt: Slack
    - src: kubernetes.svg
      alt: Kubernetes
    - src: fluentd.svg
      alt: Fluentd

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    cncf:
      logo: cncf-black.svg
      cncfLink: https://cncf.io
      level: Sandbox
      levelLink: https://github.com/cncf/toc/blob/master/process/sandbox.md 
    menu:  
    - title: Features
      url: "#features"
    - title: About
      url: "#about"
    - title: Download
      url: "#download"
    - title: GitHub
      url: https://github.com/falcosecurity/falco
    - title: Docs
      url: https://github.com/falcosecurity/falco/wiki
  sectionAbout:
    title: About Falco.
    summary: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  section1:
    title: Key Features.
    subtitle: 
    tiles:
    - title: Platform Aware
      icon: check.png
      text: Build rules specific to your Cloud Native platforms to enforce policy across all your containers & microservices.
    - title: Container-native
      icon: box.png
      text: Runtime Security built for containers. Built from the ground up to natively support containerized applications.
    - title: Deep Visibility
      icon: scalable.png
      text: Complete container visibility through a single sensor. Gain insight into application and container behavior. 
  section2:
    title: Downloads + Resources.
    subtitle: Get started today, contribute to the open source project, & learn more.
    resources:
    - title: CONTRIBUTE
      text: Jump over to our GitHub page to contribute to our open source ecosystem.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: group.png
      buttonText: Sysdig Falco Github
      buttonLink: /
    - title: Download
      text: Get started with our Falco installation guide.
      icon: download.png
      buttonText: Sysdig Falco Install Guide
      buttonLink: /
    - title: Documentation
      text: Visit our wiki where you can find information about sysdig, csysdig, and their APIs.
      icon: documentation-2.png
      buttonText: Sysdig Falco Wiki
      buttonLink: /
  footer:
    # Logo (from /images/logos/___)
    copyright: Copyright 2018, The Falco Authors
